config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 100
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path              /var/fluent-bit/state/flb-storage/
        storage.sync              normal
        storage.checksum          off
        storage.backlog.mem_limit 5M
        net.dns.resolver          LEGACY

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name                tail
        Tag                 application-all.*
        Exclude_Path        /var/log/containers/running-container-report-*, /var/log/containers/cloudwatch-agent*, /var/log/containers/fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
        Path                /var/log/containers/*.log
        Docker_Mode         On
        Docker_Mode_Flush   5
        Docker_Mode_Parser  container_firstline
        multiline.parser    docker, cri
        # Parser            docker
        DB                  /var/fluent-bit/state/flb_container.db
        Mem_Buf_Limit       100MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Rotate_Wait         30
        storage.type        filesystem
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 application-container-report.*
        Path                /var/log/containers/running-container-report-*
        Docker_Mode         On
        Docker_Mode_Flush   5
        Docker_Mode_Parser  container_firstline
        multiline.parser    docker, cri
        DB                  /var/fluent-bit/state/flb_ansible_container.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        storage.type        filesystem
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 application-all.*
        Path                /var/log/containers/fluent-bit*
        multiline.parser    docker, cri
        DB                  /var/fluent-bit/state/flb_log.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 application-all.*
        Path                /var/log/containers/cloudwatch-agent*
        Docker_Mode         On
        Docker_Mode_Flush   5
        Docker_Mode_Parser  cwagent_firstline
        Parser              docker
        DB                  /var/fluent-bit/state/flb_cwagent.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 dataplane.tail.*
        Path                /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
        multiline.parser    docker, cri
        DB                  /var/fluent-bit/state/flb_dataplane_tail.db
        Mem_Buf_Limit       100MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Rotate_Wait         30
        storage.type        filesystem
        Read_from_Head      Off

    [INPUT]
        Name                systemd
        Tag                 dataplane.systemd.*
        Systemd_Filter      _SYSTEMD_UNIT=docker.service
        Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter      _SYSTEMD_UNIT=kubeproxy.service
        Systemd_Filter      _SYSTEMD_UNIT=containerd.service
        DB                  /var/fluent-bit/state/systemd.db
        Path                /var/log/journal
        Read_From_Tail      On

    [INPUT]
        Name                tail
        Tag                 custom.aide
        Path                /var/log/aide/aide.log
        multiline.parser    aide
        DB                  /var/fluent-bit/state/flb_aide.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 custom.audit*
        Path                /var/log/audit/audit.log*
        DB                  /var/fluent-bit/state/flb_audit.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 custom.auth*
        Path                /var/log/auth.log
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_auth.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 custom.clamscan
        Path                /var/log/clamscan.log
        multiline.parser    clamscan
        DB                  /var/fluent-bit/state/flb_clamscan.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 custom.cron
        Path                /var/log/cron.log
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_cron.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 custom.kern
        Path                /var/log/kern.log
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_kern.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 custom.mail
        Path                /var/log/mail.log
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_mail.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 custom.syslog
        Path                /var/log/syslog
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_syslog.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 host.dmesg
        Path                /var/log/dmesg
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_dmesg.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 host.messages
        Path                /var/log/messages
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_messages.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

    [INPUT]
        Name                tail
        Tag                 host.secure
        Path                /var/log/secure
        Parser              syslog
        DB                  /var/fluent-bit/state/flb_secure.db
        Mem_Buf_Limit       10MB
        Skip_Long_Lines     On
        Refresh_Interval    10
        Read_from_Head      Off

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name                kubernetes
        Match               application-all.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     application-all.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Labels              On
        Annotations         On
        Buffer_Size         64K

    [FILTER]
        Name                kubernetes
        Match               application-container-report.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     application-container-report.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Labels              On
        Annotations         On

    [FILTER]
        Name                modify
        Match               dataplane.systemd.*
        Rename              _HOSTNAME                   hostname
        Rename              _SYSTEMD_UNIT               systemd_unit
        Rename              MESSAGE                     message
        Remove_regex        ^((?!hostname|systemd_unit|message).)*$

    [FILTER]
        Name                aws
        Match               dataplane.*
        imds_version        v2

    [FILTER]
        Name                aws
        Match               host.*
        imds_version        v2

    [FILTER]
        Name                aws
        Match               custom.*
        imds_version        v2

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name                cloudwatch_logs
        Match               application-all.*
        region              ${REGION}
        log_group_name      /aws/containerinsights/${SEEDNAME}/application
        log_stream_prefix   ${HOSTNAME}-
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               application-container-report.*
        region              ${REGION}
        log_group_name      /aws/containerinsights/${SEEDNAME}/container-report
        log_stream_prefix   ${HOSTNAME}-
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               dataplane.*
        region              ${REGION}
        log_group_name      /aws/containerinsights/${SEEDNAME}/dataplane
        log_stream_prefix   ${HOSTNAME}-
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               host.*
        region              ${REGION}
        log_group_name      /aws/containerinsights/${SEEDNAME}/host
        log_stream_prefix   ${HOSTNAME}-
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.aide
        region              ${REGION}
        log_group_name      /var/log/aide
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.audit*
        region              ${REGION}
        log_group_name      /var/log/audit
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.auth*
        region              ${REGION}
        log_group_name      /var/log/auth
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.clamscan
        region              ${REGION}
        log_group_name      /var/log/clamscan
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.cron
        region              ${REGION}
        log_group_name      /var/log/cron
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.kern
        region              ${REGION}
        log_group_name      /var/log/kern
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.mail
        region              ${REGION}
        log_group_name      /var/log/mail
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10

    [OUTPUT]
        Name                cloudwatch_logs
        Match               custom.syslog
        region              ${REGION}
        log_group_name      /var/log/syslog
        log_stream_name     ${SEEDNAME}
        auto_create_group   true
        extra_user_agent    container-insights
        workers             1
        auto_retry_requests On
        retry_limit         10
